### ISSUE TITLE
Link to Gherkin returns 500 error

### ISSUE THREAD

**Issue by Lachie-Young** [souranalytics/souranalytics#1]
Hello,

When on the Sour Analytics homepage, clicking on the link to gherkin.souranalytics.com results in a 500 error page.
See: https://imgur.com/a/Uahak5B

**Comment by alizahid** [comment]
@Lachie-Young Hey, thanks for your interest. Sour Analytics (including Pickle v2 and Gherkin) aren't actually ready.

The v1 of Pickle is available at https://pickle.sh.

Stay tuned on Twitter ([@souranalytics](https://twitter.com/souranalytics)) for when the apps come out!
